spring:
  application:
    name: LanchasNobre
  datasource:
    url: jdbc:mysql://localhost:3307/lancha_db?createDatabaseIfNotExist=true
    username: root
    password: ""  # senha vazia
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: matheus
      password: teste
